refactor: inprove library and log

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,10 +2,12 @@
 #
 # bootstrap installs things.
 
-cd "$(dirname "$0")/.."
-DOTFILES_ROOT=$(pwd)
-
-set -e
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in pipeline.
+set -o pipefail
 
 echo ""
 echo "                       _oo0oo_"
@@ -33,117 +35,49 @@ echo "     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 echo ""
 echo ""
 
-source lib/lib.sh
-
-link_file() {
-	local src=$1 dst=$2
-
-	local overwrite= backup= skip=
-	local action=
-
-	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
-
-		if [[ "$overwrite_all" == "false" ]] && [[ "$backup_all" == "false" ]] && [[ "$skip_all" == "false" ]]; then
-			local currentSrc="$(readlink $dst)"
-
-			if [[ "$currentSrc" == "$src" ]]; then
-				skip=true
-			else
-				user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
-                    [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-				read -n 1 action
-
-				case "$action" in
-					o)
-						overwrite=true
-						;;
-					O)
-						overwrite_all=true
-						;;
-					b)
-						backup=true
-						;;
-					B)
-						backup_all=true
-						;;
-					s)
-						skip=true
-						;;
-					S)
-						skip_all=true
-						;;
-					*) ;;
-				esac
-			fi
-
-		fi
-
-		overwrite=${overwrite:-$overwrite_all}
-		backup=${backup:-$backup_all}
-		skip=${skip:-$skip_all}
-
-		if [[ "$overwrite" == "true" ]]; then
-			rm -rf "$dst"
-			success "removed $dst"
-		fi
-
-		if [[ "$backup" == "true" ]]; then
-			mv "$dst" "${dst}.backup"
-			success "moved $dst to ${dst}.backup"
-		fi
-
-		if [[ "$skip" == "true" ]]; then
-			success "skipped $src"
-		fi
-	fi
-
-	if [[ "$skip" != "true" ]]; then # "false" or empty
-		ln -s "$1" "$2"
-		success "linked $1 to $2"
-	fi
-}
-
+ROOT_PATH="$(dirname $(dirname ${BASH_SOURCE}))"
+source ${ROOT_PATH}/lib/init.sh
 
 install_ohmyzsh() {
 	if [[ ! -d ~/.oh-my-zsh ]]; then
-		info 'installing oh-my-zsh'
+		log::status 'installing oh-my-zsh'
 		# sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
 		git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
 	fi
 }
 
 install_dotfiles() {
-	info 'installing dotfiles'
+	log::status 'installing dotfiles'
 
 	local overwrite_all=false backup_all=false skip_all=false
-	for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink'); do
+	for src in $(find "$DOT_ROOT/" -maxdepth 2 -name '*.symlink'); do
 		dst="$HOME/.$(basename "${src%.*}")"
-		link_file "$src" "$dst"
+		util::link_file "$src" "$dst"
 	done
 }
 
 install_ohmyzsh
 install_dotfiles
 
-info "installing dependencies"
-if source script/dot; then
-	success "dependencies installed"
+log::status "installing dependencies"
+if ./script/dot; then
+	log::status "dependencies installed"
 else
-	fail "error installing dependencies"
+	log::error_exit "error installing dependencies"
 fi
 
-success "===============> All installed! <==============="
+log::status "The installation is complete !!"
 
 TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
 if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
 	# If this platform provides a "chsh" command (not Cygwin), do it, man!
-	if command_exists chsh; then
-		success "Time to change your default shell to zsh!"
+	if util::command_exists chsh; then
+		log::status "Time to change your default shell to zsh!"
 		chsh -s $(grep "/zsh$" /etc/shells | tail -1)
 		# Else, suggest the user do so manually.
 	else
-		info "I can't change your shell automatically because this system does not have chsh."
-		info "Please manually change your default shell to zsh!"
+		log::status "I can't change your shell automatically because this system does not have chsh."
+		log::status "Please manually change your default shell to zsh!"
 	fi
 fi
 
diff --git a/script/dot b/script/dot
--- a/script/dot
+++ b/script/dot
@@ -5,41 +5,44 @@
 # `dot` handles installation, updates, things like that. Run it periodically
 # to make sure you're on the latest and greatest.
 
-set -e
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in pipeline.
+set -o pipefail
 
 ROOT_PATH="$(dirname $(dirname ${BASH_SOURCE}))"
-source $ROOT_PATH/lib/lib.sh
+source ${ROOT_PATH}/lib/init.sh
 
-cd $ROOT_PATH
+cd ${DOT_ROOT}
 
-info "preparing the operating system"
-sh $HOME/.dotfiles/os/prepare.sh
-success "The operating system is ready"
+log::status "preparing the operating system"
+./os/prepare.sh
+log::status "The operating system is ready"
 
-installers=$(find_installer | tr " " "\n")
+installers=($(util::find_installer | tr " " "\n"))
 
 lang=("python ruby go")
 
 # insatll language support
-for installer in $installers
-do
-    if [[ ${lang[@]} =~ $installer ]]; then
-        info "$installer installing"
-        sh $HOME/.dotfiles/$installer/install.sh
-        success "$installer installed"
-    fi
+for installer in ${installers[@]}; do
+	if [[ ${lang[@]} =~ ${installer} ]]; then
+		log::status "${installer} installing"
+		bash $HOME/.dotfiles/${installer}/install.sh
+		log::status "${installer} installation is complete"
+	fi
 done
 
 # install others
-for installer in $installers
-do
-    if [[ ${lang[@]} =~ $installer ]]; then
-        # skip os and python
-        continue
-    fi
-    info "$installer installing"
-    sh $HOME/.dotfiles/$installer/install.sh
-    success "$installer installed"
+for installer in ${installers[@]}; do
+	if [[ ${lang[@]} =~ ${installer} ]]; then
+		# skip os and python
+		continue
+	fi
+	log::status "${installer} installing"
+	bash $HOME/.dotfiles/${installer}/install.sh
+	log::status "${installer} installation is complete"
 done
 
 cd -
